version: '3'

services:
  subito:
    build: .
    environment:
      PUSHBULLET_API_KEY: ${PUSHBULLET_API_KEY}
    volumes: 
      - ${PWD}/tempfiles:/usr/src/app/tempfiles
    restart: unless-stopped